#!/usr/bin/env bash
echo "|fqdn|type|record|"
echo "|----|----|------|"
for arg in $@;do
  ANSWER_SECTION=`dig @8.8.8.8 ${arg} any +noall +ans|awk 'NR>4{printf "|" $1 "|" $4 "|"; {for(i=5; i<=NF; i++) printf $i " ";} print "|";}'`
  if [ -n "${ANSWER_SECTION}" ]; then echo "${ANSWER_SECTION}" ; else echo "|${arg} | | |"; fi
done
